language: rust
rust:
    - stable
    - beta
    - nightly
matrix:
    allow_failures:
        - rust: nightly
evn:
    - TEST_DIR=knn
    - TEST_DIR=genome
script: cd $TEST_DIR && cargo test --verbose
