language: rust
rust:
    - stable
    - beta
    - nightly
matrix:
    allow_failures:
        - rust: nightly
env:
    - TEST_DIR=guessing_game
    - TEST_DIR=knn
    - TEST_DIR=genome
    - TEST_DIR=prod_cons
    - TEST_DIR=fasta
script: cd $TEST_DIR && cargo test --verbose
